version: '3.7'

services:
  db:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    image: credit_service_postgres:development
    restart: unless-stopped
    container_name: credit_service_postgres_development
    volumes:
      - credit_service_postgres_development:/var/lib/postgresql/data
    ports:
      - "${HOST}:${DB_PORT}:${DB_PORT}"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}", "-p", "${DB_PORT}"]
      interval: 10s
      timeout: 3s
      start_period: 60s
      retries: 5
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: credit_service_api:development
    container_name: credit_service_api_development
    command: python manage.py runserver ${CONTAINER_HOST}:${CONTAINER_PORT}
    volumes:
      - .:/app
    ports:
      - "${HOST}:${PORT}:${CONTAINER_PORT}"
    env_file:
      - ./.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${CONTAINER_HOST}:${CONTAINER_PORT}/api/healthcheck"]
      interval: 10s
      timeout: 3s
      start_period: 60s
      retries: 5

volumes:
  credit_service_postgres_development:
