# Generated by Django 4.2.2 on 2023-06-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'loan_application',
                'verbose_name_plural': 'loan_applications',
                'db_table': 'loan_application',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'manufacturer',
                'verbose_name_plural': 'manufacturers',
                'db_table': 'manufacturer',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(db_column='manufacturer', on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='api.manufacturer')),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
                'db_table': 'goods',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.OneToOneField(db_column='loan_application', on_delete=django.db.models.deletion.CASCADE, related_name='loan_application_contract', to='api.loanapplication')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'db_table': 'contract',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LoanApplicationGoods',
            fields=[
                ('goods', models.OneToOneField(db_column='goods', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='goods', serialize=False, to='api.goods')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(db_column='loan_application', on_delete=django.db.models.deletion.CASCADE, related_name='loan_application_goods', to='api.loanapplication')),
            ],
            options={
                'verbose_name': 'loan_application_goods',
                'verbose_name_plural': 'loan_applications_goods',
                'db_table': 'loan_application_goods',
                'ordering': ('-created', 'loan_application'),
            },
        ),
    ]
